"""add practice_skill table

Revision ID: 08ad9636c3f1
Revises: 2ad0ab9b14b8
Create Date: 2026-06-29 03:22:53.665514
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ad9636c3f1'
down_revision: Union[str, None] = '2ad0ab9b14b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_skill',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_phoneme', sa.String(length=16), nullable=False),
    sa.Column('current_difficulty', sa.String(length=20), nullable=False),
    sa.Column('mastery_level', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('rolling_ss', sa.Float(), nullable=True),
    sa.Column('consecutive_low', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_phoneme', name='uq_practice_skill_user_phoneme')
    )
    op.create_index(op.f('ix_practice_skill_guid'), 'practice_skill', ['guid'], unique=True)
    op.create_index(op.f('ix_practice_skill_user_id'), 'practice_skill', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_skill_user_id'), table_name='practice_skill')
    op.drop_index(op.f('ix_practice_skill_guid'), table_name='practice_skill')
    op.drop_table('practice_skill')
    # ### end Alembic commands ###
