"""add disfluency_occurrence table

Revision ID: 2ad0ab9b14b8
Revises: 4ff54d3a6773
Create Date: 2026-06-29 02:09:10.359860
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad0ab9b14b8'
down_revision: Union[str, None] = '4ff54d3a6773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disfluency_occurrence',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.Column('disfluency_type', sa.String(length=20), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=True),
    sa.Column('sound', sa.String(length=16), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('timestamp_start', sa.Float(), nullable=True),
    sa.Column('timestamp_end', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disfluency_occurrence_disfluency_type'), 'disfluency_occurrence', ['disfluency_type'], unique=False)
    op.create_index(op.f('ix_disfluency_occurrence_guid'), 'disfluency_occurrence', ['guid'], unique=True)
    op.create_index(op.f('ix_disfluency_occurrence_session_id'), 'disfluency_occurrence', ['session_id'], unique=False)
    op.create_index(op.f('ix_disfluency_occurrence_sound'), 'disfluency_occurrence', ['sound'], unique=False)
    op.create_index(op.f('ix_disfluency_occurrence_user_id'), 'disfluency_occurrence', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disfluency_occurrence_user_id'), table_name='disfluency_occurrence')
    op.drop_index(op.f('ix_disfluency_occurrence_sound'), table_name='disfluency_occurrence')
    op.drop_index(op.f('ix_disfluency_occurrence_session_id'), table_name='disfluency_occurrence')
    op.drop_index(op.f('ix_disfluency_occurrence_guid'), table_name='disfluency_occurrence')
    op.drop_index(op.f('ix_disfluency_occurrence_disfluency_type'), table_name='disfluency_occurrence')
    op.drop_table('disfluency_occurrence')
    # ### end Alembic commands ###
