"""add practice_attempt table

Revision ID: 4ff54d3a6773
Revises: 4a1b5c6d7e8f
Create Date: 2026-06-28 19:05:30.448866
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ff54d3a6773'
down_revision: Union[str, None] = '4a1b5c6d7e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_attempt',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=True),
    sa.Column('reference_phrase', sa.Text(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('coverage_score', sa.Float(), nullable=True),
    sa.Column('stutter_frequency_percent', sa.Float(), nullable=True),
    sa.Column('words_per_minute', sa.Float(), nullable=True),
    sa.Column('dominant_disfluency', sa.String(length=50), nullable=True),
    sa.Column('should_retry', sa.Boolean(), nullable=True),
    sa.Column('child_age', sa.Integer(), nullable=True),
    sa.Column('disfluencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recognition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id'], ['disfluency_phrase.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_attempt_guid'), 'practice_attempt', ['guid'], unique=True)
    op.create_index(op.f('ix_practice_attempt_phrase_id'), 'practice_attempt', ['phrase_id'], unique=False)
    op.create_index(op.f('ix_practice_attempt_user_id'), 'practice_attempt', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_attempt_user_id'), table_name='practice_attempt')
    op.drop_index(op.f('ix_practice_attempt_phrase_id'), table_name='practice_attempt')
    op.drop_index(op.f('ix_practice_attempt_guid'), table_name='practice_attempt')
    op.drop_table('practice_attempt')
    # ### end Alembic commands ###
