"""add role, patient ailments, delivery, proficiency

Revision ID: 6c7f011e9823
Revises: 2f03c9f5dceb
Create Date: 2026-06-27 14:19:14.318345
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6c7f011e9823'
down_revision: Union[str, None] = '2f03c9f5dceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proficiency_test',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    # Reuse the existing difficulty_enum type (made by the first migration).
    # postgresql.ENUM honours create_type=False; the generic sa.Enum ignores it.
    sa.Column('assigned_difficulty', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficulty_enum', create_type=False), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proficiency_test_guid'), 'proficiency_test', ['guid'], unique=True)
    op.create_index(op.f('ix_proficiency_test_user_id'), 'proficiency_test', ['user_id'], unique=False)
    op.create_table('phrase_delivery',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.Enum('PROFICIENCY_TEST', 'GAME', name='delivery_context_enum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id'], ['disfluency_phrase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrase_delivery_guid'), 'phrase_delivery', ['guid'], unique=True)
    op.create_index(op.f('ix_phrase_delivery_phrase_id'), 'phrase_delivery', ['phrase_id'], unique=False)
    op.create_index(op.f('ix_phrase_delivery_user_id'), 'phrase_delivery', ['user_id'], unique=False)
    op.create_table('proficiency_test_response',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id'], ['disfluency_phrase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['proficiency_test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proficiency_test_response_guid'), 'proficiency_test_response', ['guid'], unique=True)
    op.create_index(op.f('ix_proficiency_test_response_test_id'), 'proficiency_test_response', ['test_id'], unique=False)
    op.create_table('patient_ailment',
    sa.Column('patient_detail_id', sa.Integer(), nullable=False),
    sa.Column('ailment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ailment_id'], ['ailment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_detail_id'], ['patient_detail.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_detail_id', 'ailment_id')
    )
    # op.add_column does NOT auto-create the enum type (unlike create_table),
    # so create user_role_enum explicitly first, then add the column using it.
    user_role_enum = postgresql.ENUM('PATIENT', 'DOCTOR', name='user_role_enum', create_type=False)
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user_account', sa.Column('role', user_role_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'role')
    op.drop_table('patient_ailment')
    op.drop_index(op.f('ix_proficiency_test_response_test_id'), table_name='proficiency_test_response')
    op.drop_index(op.f('ix_proficiency_test_response_guid'), table_name='proficiency_test_response')
    op.drop_table('proficiency_test_response')
    op.drop_index(op.f('ix_phrase_delivery_user_id'), table_name='phrase_delivery')
    op.drop_index(op.f('ix_phrase_delivery_phrase_id'), table_name='phrase_delivery')
    op.drop_index(op.f('ix_phrase_delivery_guid'), table_name='phrase_delivery')
    op.drop_table('phrase_delivery')
    op.drop_index(op.f('ix_proficiency_test_user_id'), table_name='proficiency_test')
    op.drop_index(op.f('ix_proficiency_test_guid'), table_name='proficiency_test')
    op.drop_table('proficiency_test')
    # Drop the enum types created in this migration (table drops don't remove
    # them). Do NOT drop difficulty_enum — it belongs to the first migration.
    postgresql.ENUM(name='user_role_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='delivery_context_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
