"""Seed 100 Story Teller stories into `disfluency_phrase` (idempotent).

100 narrative-retell stories for the Story Teller game:
  34 EASY   (40-80 words,  ages 5-7)
  33 MEDIUM (90-150 words, ages 8-11)
  33 HARD   (150-220 words, ages 12-15)

Rows use exercise_type='STORY_TELLER', target_phoneme=NULL (open-ended retell, not
phoneme-targeted), the matching difficulty, and the neutral 'Reading' ailment_type
(stories aren't tied to a disfluency sub-type). The story text lives in `sentence`.

Prereq: migration b3c4d5e6f7a8 (exercise_type column) applied.
Run:    python -m scripts.seed_story_teller
Idempotent: matched by (exercise_type, sentence). Set AILMENT_TYPE_ID to override.
"""

import os

from sqlalchemy import select, text

from app.db.base import SessionLocal
from app.models.disfluency import Difficulty, DisfluencyPhrase

# (difficulty, story_text)
STORIES: list[tuple[str, str]] = [
    ("EASY", "Pip the puppy chased a butterfly and got lost in the tall grass. He did not know the way home. He sniffed the ground and found the smell of his warm bed. Pip followed the smell down the path. Soon he saw his little house. His family gave him a big hug. Pip wagged his tail and was so happy to be home again."),
    ("EASY", "It was Mia's birthday. Her friends were very quiet and hiding behind the couch. Mia opened the door and it looked dark. Then everyone jumped up and shouted, \"Surprise!\" Mia saw a big cake with pink candles. She smiled so wide. She blew out the candles and made a wish. Everyone laughed and sang. It was the best birthday Mia ever had."),
    ("EASY", "Leo went to the zoo with his mom. First they saw the tall giraffes eating leaves. Then they watched the funny monkeys swing. Leo wanted to see the lion most of all. They walked to the big rock. The lion opened his mouth and gave a loud roar. Leo giggled and clapped his hands. He waved goodbye and said the zoo was his favorite place."),
    ("EASY", "Sam woke up and looked outside. White snow covered everything! He put on his warm coat and boots. Sam rolled a big snowball, then a smaller one on top. He made a happy snowman with a carrot nose. His mom brought hot cocoa in a cup. Sam sipped it and looked at his snowman. He felt warm and cozy on the snowy winter day."),
    ("EASY", "It was Ava's first day at a new school. She sat alone and felt shy. A girl named Rosa came over with a smile. \"Do you want to color with me?\" Rosa asked. Ava said yes. They drew rainbows and shared crayons. At playtime they ran and laughed together. Now Ava was not shy anymore. She had a brand new friend named Rosa."),
    ("EASY", "Ben found one tiny seed that sparkled like gold. He planted it in the soft dirt. Every day he gave it water and sunshine. He waited and waited. One morning a green sprout popped up! It grew tall and taller. Then a huge flower bloomed with bright colors. It smelled sweet like candy. Ben smiled at his magic seed and told all his friends."),
    ("EASY", "Robo was a little robot with bright blue lights. Today the toys were all over the floor. Robo beeped and rolled around the room. He picked up the blocks and put them in the box. He found the lost teddy bear too. The room was clean and tidy. The family clapped for Robo. Robo blinked happily and beeped, \"I love to help!\""),
    ("EASY", "Nina went to the beach with her dad. The sand was warm on her toes. She built a tall sandcastle with a shell on top. Then a wave came and tickled her feet. Nina laughed and jumped in the water. She found a pretty pink shell to keep. At the end they watched the sun go down. It was a perfect beach day."),
    ("EASY", "Milo was a small mouse who wanted some cheese. The cheese was way up high on the table. Milo felt a little scared. But he took a deep breath and climbed up the leg. Step by step he went higher. At last he reached the yummy cheese! Milo was so proud. He carried it home and shared it with his family."),
    ("EASY", "Grandpa gave Jake an old map of the backyard. It had a big red X on it. Jake followed the map past the tree and the flowers. He counted ten steps to the X. Then he began to dig with his shovel. Clink! He found a little box. Inside were shiny gold coins made of chocolate. Jake grinned and shared the treasure with Grandpa."),
    ("EASY", "Lily and her mom planted seeds in the garden. Lily watered them every single day. At first the dirt looked plain and brown. Lily waited and stayed patient. One sunny morning, red and yellow flowers popped up everywhere. Bees buzzed and butterflies danced around them. The garden was full of pretty colors. Lily smiled because her flowers finally bloomed."),
    ("EASY", "Milo flew his red kite in the park. The wind pulled hard, and the kite went up, up, up! Soon it was higher than the tall trees. Milo held the string tight. He did not let go. Slowly, he wound the string in. The kite came down, down, down. It landed softly in his arms. Milo hugged his kite and smiled."),
    ("EASY", "Pip was a small puppy who wanted to learn a trick. His girl Anna said, \"Sit, Pip!\" But Pip just wagged his tail. Anna tried again and gave him a treat. Pip watched her hand. Slowly, he sat down. \"Good dog, Pip!\" Anna cheered. Pip barked happily. He had learned his very first trick, and he felt so proud."),
    ("EASY", "Ella went to visit Grandma on Sunday. Grandma opened the door with a big warm hug. \"Come in!\" she said. Inside, the kitchen smelled sweet. They baked round cookies together and licked the spoon. The cookies came out golden and hot. Ella and Grandma sat by the window and ate two each. \"I love you, Grandma,\" said Ella. Grandma smiled."),
    ("EASY", "Finn was a little fish who lived near the coral reef. One morning, he wanted to explore. He swam past pink coral and waving green plants. He met a friendly crab and a slow sea turtle. \"Hello!\" said Finn. They swam together through the bright water. When the sun went down, Finn swam home. He told his mom about all his new friends."),
    ("EASY", "Sam sat in his little rocket ship. \"Three, two, one, blast off!\" he shouted. The rocket zoomed up past the clouds and into space. Sam saw twinkling stars all around. Soon he landed softly on the moon. He jumped high in big, floating hops. He waved at Earth far away. Then Sam flew back home for supper, grinning the whole way."),
    ("EASY", "Today was the big soccer game. Zoe's team was tied. Her heart beat fast. Then the ball rolled right to her feet! Zoe ran and gave it a big kick. The ball flew into the goal. \"Goal!\" everyone cheered. Zoe's team jumped and hugged. After the game, both teams shook hands and shared cold water. Zoe felt happy and warm inside."),
    ("EASY", "The school was having a bake sale. Leo baked muffins with his dad. They packed them in a big blue box. At school, Leo set up a little table. \"Muffins, one dollar!\" he called. Lots of friends came to buy them. Soon every muffin was gone. The money would help buy new books for the library. Leo felt proud and happy."),
    ("EASY", "On a warm summer night, a tiny firefly woke up. She blinked her small light on and off. Other fireflies floated in the dark yard. \"Come play!\" they blinked. Together they made the whole garden sparkle. A little girl watched from her window and smiled. When morning came, the firefly rested on a leaf. She would light up again the next night."),
    ("EASY", "In the autumn field stood a scarecrow named Straw. His job was to watch the pumpkins. The leaves turned red and gold around him. A little bird landed on his hat. \"Hello, friend,\" said Straw. The bird chirped and stayed all day. Straw did not feel lonely anymore. Each morning the bird came back. They watched the pumpkins grow, happy together."),
    ("EASY", "Maya opened a library book about the sea. As she read, she felt like she was really there! She saw blue waves and jumping dolphins. She walked on soft golden sand. A dolphin waved its fin at her. Then Maya turned the last page and looked up. She was back in the cozy library. \"What a fun trip!\" she said, hugging her book."),
    ("EASY", "Jack built a happy snowman named Frosty. But the spring sun grew warm. \"I don't want Frosty to melt,\" said Jack. He thought hard. Then he ran and got his crayons and paper. Jack drew a big picture of Frosty. Now Frosty could stay forever on his wall! Jack hung the picture by his bed and waved goodnight to his snowman friend."),
    ("EASY", "Mia wanted to win the sandcastle contest. She dug and patted the sand, but her tower kept falling down. A boy named Leo showed her how to add water. Together they built a tall castle with a shell on top. The judge smiled. \"This is the best one!\" she said. Mia and Leo shared the prize and became good friends."),
    ("EASY", "Ruby made a lemonade stand on a hot day. But no one came to buy. She felt a little sad. Then she gave a free cup to a tired mail carrier. He told his friends how good it was. Soon a big line formed! Ruby sold every cup. She learned that being kind can bring wonderful surprises."),
    ("EASY", "Bella held her red balloon tight. But the wind tugged it away, up into the sky! She watched it float over the trees. A kind bird flew down carrying the string in its beak. It gently brought the balloon back to Bella. She hugged the bird and said thank you. Then she held her balloon very, very tight."),
    ("EASY", "Spark was a tiny dragon who could not roar. The other dragons laughed. But one cold night, the village fire went out. Spark breathed a warm little flame and lit it again. Everyone cheered! \"Small dragons can do big things,\" said the mayor. Spark smiled and felt proud. From that day, he was the happiest dragon of all."),
    ("EASY", "Tilly the turtle entered the big race. \"You are too slow!\" said the rabbit. When the race began, Tilly walked step by step. The rabbit ran fast, then stopped for a nap. Tilly kept going and going. She crossed the finish line first! Everyone clapped. Tilly learned that going slow and steady can still win the day."),
    ("EASY", "One night a little star slipped and fell from the sky. It landed softly in a garden. A girl named Ana found it glowing in the grass. The star was scared and lost. Ana climbed the tallest hill and lifted it high. With a gentle push, the star flew home. It winked down at Ana every single night after."),
    ("EASY", "The town was dry and the flowers drooped. A small cloud floated by and saw the sad plants. \"I can help!\" it said. The cloud puffed up big and let down a soft, cool rain. The flowers lifted their heads. The children danced and laughed. The little cloud felt happy and floated on to help another thirsty town."),
    ("EASY", "Old Mr. Bell was a kind clockmaker. He fixed clocks for everyone in town. One day a girl brought a broken clock that once belonged to her grandma. Mr. Bell worked carefully all afternoon. Tick, tock! The clock came alive again. The girl hugged him with happy tears. Mr. Bell smiled, glad he could bring back a special sound."),
    ("EASY", "Sam kept the lighthouse by the sea. One night a big storm rolled in. Rain poured and the wind howled. A little boat was lost on the dark water. Sam turned the great lamp on bright. Its light showed the way. The boat sailed safely to shore. The sailors waved and thanked Sam, the brave lighthouse keeper."),
    ("EASY", "A tiny seed landed high on a rocky mountain. \"Nothing grows here,\" said the wind. But the seed did not give up. Rain fell and sun shone. Slowly, a small green sprout pushed up. It grew into a strong little tree. Birds came to rest in its branches. The tiny seed had made the lonely mountain a happy home."),
    ("EASY", "A proud king asked a painter for a picture of himself. \"Make me look grand!\" he said. The painter painted the king smiling and helping a child. The king frowned. \"That is not grand!\" But the people loved it. \"This is our kind king!\" they cheered. The king looked again and smiled. He learned that being kind is truly grand."),
    ("EASY", "Mika loved to build things. One rainy day, she wanted dry socks fast. She gathered a fan, a box, and some string. Snap, click, whirr! Her little sock dryer began to spin. At first, the socks flew everywhere and made her giggle. Mika fixed one string, and this time the socks came out warm and dry. \"I did it!\" she cheered, hugging her marvelous machine."),
    ("MEDIUM", "Pepper the puppy chased a butterfly out of the yard. She ran and ran until the streets looked strange. She did not know how to get home. Pepper sat down and felt scared. Then she lifted her nose and sniffed the air. She smelled her favorite thing: the fresh bread from the bakery near her house! Step by step, Pepper followed the yummy smell. She turned one corner, then another. Soon she saw the red door of her home. Her family was outside calling her name. Pepper barked happily and ran straight into their arms. They hugged her tight and gave her a warm bowl of dinner. From that day on, Pepper never chased butterflies past the gate. She learned that home was the best place to be, and her nose always knew the way."),
    ("MEDIUM", "Mia woke up on her birthday feeling sad. The house was very quiet. No balloons, no cake, and everyone seemed busy. She thought her family had forgotten. All day she waited, but nobody said a word. When evening came, her mom asked her to fetch a book from the backyard. Mia opened the door slowly. Suddenly, the yard lit up with twinkling lights! Her friends and family jumped out and shouted, \"Surprise!\" There was a big chocolate cake, colorful balloons, and her favorite music playing. Mia laughed so hard that happy tears filled her eyes. They had planned the whole thing to trick her. She hugged everyone and blew out her candles. It was the best surprise she had ever had. Mia learned that sometimes the quiet is just a secret waiting to become a wonderful gift."),
    ("MEDIUM", "Sam had never been to the zoo before. He held his dad's hand as they walked through the big gates. First, they saw the tall giraffes stretching their long necks to eat leaves. Sam giggled at their spotted coats. Next, they watched the monkeys swing from branch to branch, playing games in the trees. Sam pretended to swing too. Then they found the penguins waddling by the cool water. His favorite was the sleepy lion resting in the shade. At lunchtime, Sam ate a sandwich and drew pictures of every animal he saw. Before they left, he waved goodbye to the elephants splashing in the mud. On the way home, Sam told his dad, \"That was the best day ever!\" He fell asleep in the car, dreaming of all the amazing animals he would visit again."),
    ("MEDIUM", "When Lily woke up, the whole world was white. Soft snow covered the trees, the roofs, and the yard. School was closed! Lily put on her warm coat, mittens, and a woolly hat. She ran outside with her little brother, Max. Together they rolled a big ball of snow, then a medium one, then a small one. They stacked them up to make a snowman. Lily used two buttons for eyes and a carrot for the nose. Max wrapped his own scarf around its neck. They named the snowman Frosty Fred. When they got too cold, they went inside for hot cocoa with marshmallows. Lily looked out the window at their snowman standing proudly in the yard. \"He looks so friendly,\" she said. It was a snowy day full of fun, and Lily hoped it would snow again soon."),
    ("MEDIUM", "On Monday, a new boy named Theo joined Ava's class. He sat alone at recess, looking shy and unsure. Ava remembered how scary it felt to be new. She walked over and asked, \"Do you want to play tag with us?\" Theo smiled and nodded. Soon they were running and laughing across the playground. At lunch, Ava saved a seat for him. They discovered they both loved dinosaurs and drawing comics. Theo showed Ava his sketchbook full of amazing creatures. Ava shared her crayons and they made a comic together. By the end of the day, they were giggling like old friends. Theo said, \"Thank you for being so kind. I was really nervous this morning.\" Ava grinned. \"Now you have a friend,\" she said. Making a new friend was easier than either of them thought."),
    ("MEDIUM", "Grandpa gave Noah a tiny, shiny seed. \"This one is special,\" he whispered with a wink. Noah planted it in a small pot and watered it every morning. Days passed, and nothing happened. Noah almost gave up. Then one morning, a green sprout poked through the soil. Noah cheered! Each day the plant grew taller and taller. Soon it reached the window, then the ceiling! Tiny buds appeared along the stem. One sunny morning, the buds burst open into flowers of every color, red, orange, yellow, blue, and purple, like a rainbow in his room. The whole house smelled sweet and lovely. Noah showed Grandpa, who smiled proudly. \"You cared for it with patience,\" Grandpa said, \"and that is real magic.\" Noah learned that good things grow when you give them love, water, and a little bit of time."),
    ("MEDIUM", "Emma had a little robot named Bolt. He was small enough to fit in her pocket and blinked with friendly blue eyes. One busy morning, Emma could not find her missing homework. She looked everywhere and started to worry. Bolt beeped brightly and rolled across the floor. He zipped under the bed, whirred around the desk, and found the paper hiding behind the bookshelf! Emma cheered and gave Bolt a gentle pat. Later, Bolt helped her water the plants and even reminded her to feed the cat. When Emma spilled her cereal, Bolt hummed a silly tune to cheer her up. At bedtime, Emma tucked Bolt into his charging bed. \"Thank you for helping me today,\" she said. Bolt blinked happily and beeped goodnight. Emma smiled, glad to have such a kind and helpful little friend by her side."),
    ("MEDIUM", "The sun was shining as Jack and his family arrived at the beach. Jack ran to the soft sand and felt it warm under his feet. First, he built a tall sandcastle with his mom, adding towers and a wide moat. Then he splashed in the cool waves, laughing as they tickled his toes. His dad helped him look for seashells along the shore. Jack found a pink one, a spotted one, and a big white one. Suddenly, he spotted something shiny in the sand. It was a smooth shell shaped like a heart! Jack held it up to his ear and heard the ocean's gentle hum. He decided to give it to his little sister as a gift. She hugged it happily. As the sun set, Jack packed up, tired but joyful. The beach had given him the perfect treasure."),
    ("MEDIUM", "Milo was the smallest mouse in the whole meadow. The other mice sometimes said he was too little to be brave. One evening, Milo's family ran out of food. A big storm was coming, and the pantry was empty. Milo decided to help. He crept out into the tall grass, his tiny heart pounding. He climbed over rocks and squeezed under fences. At the farmer's barn, he found a pile of golden corn. Milo picked the biggest kernel he could carry and hurried home through the wind. When he arrived, his family cheered with joy. \"You are the bravest mouse of all,\" said his mother, hugging him tight. That night, warm and safe, the mice shared the corn while the storm rumbled outside. Milo learned that being brave has nothing to do with being big. It comes from a kind and caring heart."),
    ("MEDIUM", "On a sunny Saturday, Zoe found an old map tucked inside a dusty book. It showed her own backyard with a big red X near the oak tree. \"A treasure hunt!\" she gasped. Zoe grabbed her explorer hat and followed the clues. The first clue led her to the birdbath, where a note said, \"Look under the big stone.\" Beneath the stone was another clue pointing to the garden shed. Behind the shed, she found a small wooden box wrapped in string. Her heart raced as she opened it. Inside were shiny marbles, a friendship bracelet, and a note from her grandma. It read, \"For my clever explorer. I hid these years ago, just for you.\" Zoe grinned from ear to ear. She wore the bracelet proudly and thanked her grandma with a big hug. It was the best treasure she could imagine."),
    ("MEDIUM", "Rain tapped on the windows all morning, so Ben and his sister Rosa could not play outside. At first, Ben felt bored and grumpy. Then Rosa had an idea. \"Let's build a fort!\" she said. They gathered pillows, blankets, and chairs from around the house. Together they made a giant, cozy fort in the living room. Inside, they read stories with a flashlight and told funny jokes. Their mom brought them warm popcorn and cups of apple juice. They played board games and even put on a puppet show using their socks. The rain kept falling, but Ben did not mind anymore. He was having too much fun. By afternoon, the sun peeked out and a rainbow stretched across the sky. Ben smiled and told Rosa, \"That was the best rainy day ever.\" Sometimes the coziest days happen when you stay inside together."),
    ("MEDIUM", "Every spring, Grandma's garden was the most beautiful on the street. This year, she asked Ella to help her plant it. Together they dug small holes in the soft brown soil. They tucked in tiny seeds and gentle little roots. Ella watered them carefully with her small green can. Each morning, she checked the garden before school. At first, only the dirt was there. Ella wondered if anything would grow. But slowly, tiny green leaves appeared. Then came buds, closed up tight like sleepy babies. One warm morning, Ella ran outside and gasped. The whole garden had burst into bloom! There were sunflowers, daisies, and roses of pink and red. Bees buzzed happily among the petals. Grandma hugged Ella and said, \"We did this together.\" Ella felt so proud. She had learned that with care and patience, even the smallest seed can bloom."),
    ("MEDIUM", "Maya ran across the green hill with her bright red kite. The wind grabbed it, and up it went, higher and higher. Soon the kite flew so high it looked like a tiny dot near the clouds. Maya felt the string tug hard in her hands. She worried it might fly away forever. Her older brother Sam ran over to help. Together they held the string tight and slowly, gently, they wound it back in. Little by little, the kite came down from the clouds. At last it landed softly on the grass, safe again. Maya hugged her kite and smiled. \"You almost reached the sky!\" she laughed. From then on, Maya always flew her kite with Sam. They learned that sharing a job makes even a wild wind easy to handle. It was their best afternoon all summer."),
    ("MEDIUM", "Pip was a small brown puppy with floppy ears. His owner, Ben, wanted to teach him a new trick. \"Roll over, Pip!\" Ben said. But Pip only wagged his tail and licked Ben's hand. Ben tried again the next day. He held a treat above Pip's nose and moved it slowly in a circle. Pip turned his head, but he did not roll. Ben did not give up. Every morning after school, they practiced together in the yard. On the fifth day, something amazing happened. Ben moved the treat, and Pip flopped onto his back and rolled all the way over! \"Good boy!\" Ben cheered, hugging his puppy. Pip barked happily and rolled again and again, just for fun. Ben learned that practice takes time, but it always pays off. That night, Pip slept happily, dreaming of new tricks."),
    ("MEDIUM", "On Saturday, Ella visited her grandma's cozy house. It smelled like warm sugar and cinnamon. \"Come help me bake,\" Grandma said with a smile. Ella washed her hands and put on a flowery apron. Together they mixed flour, butter, and eggs in a big blue bowl. Ella cracked an egg all by herself, and only a little shell fell in. Grandma laughed and scooped it out. They rolled the dough and cut out stars and hearts. Ella pressed sprinkles onto every cookie. Soon the kitchen was full of the sweet smell of baking. When the cookies were golden, they let them cool by the window. Ella and Grandma sat together and ate the warm cookies with cold milk. \"These are the best cookies ever,\" Ella said. Grandma hugged her tight. It was a day Ella would always remember."),
    ("MEDIUM", "Finn was a little orange fish who lived near a bright coral reef. He was curious about everything. One morning, he decided to explore a part of the reef he had never seen. He swam past purple coral and waving green seaweed. He met a friendly crab who waved a tiny claw hello. Finn saw a bright starfish resting on a rock and a school of silver fish darting by. Then he found a beautiful cave glowing with soft pink light. Inside, seahorses bobbed gently in the water. Finn had never seen anything so lovely. He wanted to tell his friends, so he swam quickly back home. \"Come see the glowing cave!\" he called. All his friends followed him through the reef. Together they explored the wonderful cave. Finn felt proud that he had found something to share with everyone he loved."),
    ("MEDIUM", "Zoe climbed into her shiny silver rocket and buckled her seatbelt tight. \"Three, two, one, blastoff!\" she said. The rocket zoomed up through the clouds and into the dark, starry sky. Zoe watched Earth grow small and blue behind her. She floated gently in her seat because there was no gravity. After a long journey, the rocket landed softly on the moon. Zoe stepped out in her puffy white spacesuit. She bounced high with every step, laughing at how light she felt. She collected a smooth gray moon rock to bring home. She planted a little flag and waved at Earth far away. Then it was time to go back. Zoe flew her rocket home and landed safely in her backyard. She showed her family the moon rock. \"I touched the moon!\" she said proudly. Everyone cheered for brave Zoe."),
    ("MEDIUM", "Leo's soccer team was playing the biggest game of the season. The score was tied, and only two minutes remained. Leo felt nervous, and his heart pounded fast. His coach knelt beside him. \"Just do your best and have fun,\" she said kindly. Leo took a deep breath and ran back onto the field. His teammate passed him the ball. Leo dribbled past two players, keeping his eyes on the goal. He could hear his friends cheering from the sideline. With one strong kick, Leo sent the ball flying. It soared past the goalkeeper and into the net! His whole team ran to hug him. They had won the game! But Leo knew it was not just his goal. \"We did it together,\" he told his friends. They walked off the field smiling. It was the best game Leo had ever played."),
    ("MEDIUM", "The whole class was excited for the school bake sale. They wanted to raise money for new library books. Priya decided to make banana muffins with her dad. They mashed ripe bananas and stirred the batter carefully. The next morning, Priya carried her muffins to school in a big basket. Tables were covered with cookies, cupcakes, and colorful cakes. Lots of families came to buy the treats. Priya smiled as customers bought her muffins one by one. Soon her basket was empty. When the bake sale ended, the teacher counted all the money. \"We raised enough for twenty new books!\" she announced. The whole class cheered loudly. Priya felt proud that her muffins had helped. A few weeks later, shiny new books arrived at the library. Priya picked one and started reading. She knew the bake sale had made her school even better."),
    ("MEDIUM", "On a warm summer night, a little firefly named Glow woke up in the tall grass. He blinked his tiny light on and off. But when he looked around, he felt shy. All the other fireflies glowed so brightly, and his light seemed small. Glow flew off alone toward the pond. There he saw a lost baby rabbit who could not find its way home in the dark. \"I can help you,\" Glow said. He flew ahead, lighting the path with his little glow. The rabbit hopped safely all the way back to its family. \"Thank you, brave firefly!\" the rabbit said. Glow felt warm and happy inside. His light suddenly seemed to shine brighter than ever. He flew back to the other fireflies, glowing proudly. Glow learned that even a small light can make a big difference on a dark night."),
    ("MEDIUM", "Sam found a dusty old book on the library's top shelf. When he opened it, something magical happened. The words began to glow, and a soft wind swirled around him. Suddenly, Sam was standing inside the story! He was on a sailing ship gliding across a bright blue sea. A friendly captain waved and let Sam steer the wheel. They sailed to a sunny island covered in palm trees. Sam helped the crew find a treasure chest buried in the warm sand. Inside was not gold, but hundreds of beautiful storybooks. \"The greatest treasure is a good story,\" the captain said. Then the page turned, and Sam found himself back in the quiet library. He hugged the magic book tight. From that day on, Sam visited the library every week. He knew that every book could take him on a brand-new adventure."),
    ("MEDIUM", "On contest day, Maya's sandcastle kept crumbling. Every tower she built slid flat before the judges arrived. Nearby, a boy named Sam had the same trouble, and both children looked ready to give up. Then Maya had an idea. \"What if we build together?\" she asked. Sam grinned and nodded. They mixed their sand with just enough seawater, then packed it firmly into buckets. Working side by side, they shaped tall towers, a wide wall, and a tiny bridge. Their two small piles became one grand castle. When the judges walked past, they stopped and smiled. Maya and Sam did not win first prize, but they won the ribbon for teamwork. As waves rolled closer, the two friends laughed and promised to build together again next summer. Sharing had made something far better than either could build alone."),
    ("MEDIUM", "Penny opened her lemonade stand on the hottest day of July. She squeezed lemons, added sugar, and stirred in cold water. But no customers came, and her arms grew tired. Just then, she noticed the mail carrier wiping sweat from his forehead as he walked his long route. Penny poured a tall cup and ran to him. \"It's free,\" she said kindly. The mail carrier drank it and smiled. \"That's the best lemonade in town!\" He told everyone he met. Soon a line formed at Penny's stand, and people chatted happily while they sipped. By evening, her jar of coins was full. Penny realized her kindness had brought all the customers. She saved half the coins and used the rest to buy more lemons. Tomorrow, she would open her stand again and share more cool, sweet cups."),
    ("MEDIUM", "At the fair, Leo held a bright red balloon on a string. Suddenly, a gust of wind tugged it free. Up, up it floated, higher than the trees. Leo felt sad watching it drift away. But the balloon seemed happy, spinning against the blue sky. A little girl below pointed up and clapped with joy. Then a bird flew close, curious about the shiny red visitor. The balloon bobbed gently, as if saying hello. Leo watched until it became a tiny dot. Instead of crying, he smiled. \"Maybe it wanted to see the whole world,\" he said. His mother squeezed his hand and bought him a new blue balloon, one he tied carefully to his wrist. That night, Leo imagined his red balloon floating over mountains and oceans, seeing wonderful things he could only dream about."),
    ("MEDIUM", "Ember was the smallest dragon in the valley. She could not roar loudly or fly very high, and the other dragons teased her gently. But Ember had one special gift: her tiny flame was warm and soft, never too hot. One cold morning, the village children were shivering because their fire had gone out. Ember flew down carefully and breathed her gentle flame onto the woodpile. Warm orange light filled the square. The children cheered and gathered close, holding out their hands. From then on, Ember became the village's favorite friend. Each winter morning, she lit the fire so everyone could stay cozy. The bigger dragons watched and learned something important. Being the biggest or loudest was not what mattered most. Ember's small, kind flame warmed more hearts than any mighty roar ever could, and that made her very proud."),
    ("MEDIUM", "Shelly the turtle wanted to join the forest race. The rabbits and deer laughed. \"You're far too slow,\" they said. But Shelly signed up anyway. When the race began, the fast animals zoomed ahead and left her behind. Along the way, though, the rabbit stopped to nap, and the deer paused to nibble berries. Shelly did not stop. Step by step, she kept moving down the path, never giving up. She crossed a stream, climbed a hill, and rounded the final bend. To everyone's surprise, Shelly reached the finish line first! The other animals cheered loudly, amazed by the little turtle. \"How did you do it?\" they asked. Shelly smiled. \"I just kept going, one small step at a time.\" That day, the whole forest learned that steady effort can beat speed, and slow Shelly became a champion."),
    ("MEDIUM", "One night, a small star slipped from the sky and landed softly in a meadow. It glowed gently in the grass, unsure how to get home. A young girl named Nora found it while chasing fireflies. \"Don't worry,\" she whispered. \"I'll help you.\" She held the warm little star and thought hard. Then she remembered the tall hill outside town. Nora carried the star to the very top and lifted it high above her head. A cool breeze swirled around them. Slowly, the star floated up, up, back toward its friends twinkling above. It winked once, as if to say thank you. Nora waved until it settled back into place among the other stars. Every night after that, Nora looked up and found her special star shining brightest of all, glad she had helped it find its way home."),
    ("MEDIUM", "The little town of Dusty Hollow had not seen rain in weeks. The gardens drooped and the river shrank. High above, a small cloud named Puff drifted by and noticed the sad, dry fields. Puff wanted to help, but he was only one tiny cloud. So he called to his cloud friends across the sky. \"Come quickly! A town needs us!\" One by one, bigger clouds gathered around Puff until the sky turned soft and gray. Then, gently, they let their rain fall. Cool drops splashed on the thirsty gardens and filled the shrinking river. The townspeople rushed outside, laughing and dancing in the rain. Flowers lifted their heads, and the grass turned green again. Puff felt happy and proud. Though he was small, he had known exactly who to ask for help, and together the clouds had saved the town."),
    ("MEDIUM", "Old Mr. Tick was the kindest clockmaker in the village. His little shop was filled with ticking clocks of every size. One winter, a poor boy named Otto pressed his nose to the window, wishing for a clock so he would never be late for school. Mr. Tick noticed and waved him inside. \"Would you like to learn?\" he asked warmly. Otto nodded eagerly. Each afternoon, the boy helped clean gears and wind springs, listening carefully to everything Mr. Tick taught. On the last day of winter, the old man handed Otto a small, shiny clock. \"You built this yourself,\" he said with a smile. Otto could hardly believe it. He hugged Mr. Tick and hurried home, his very own clock ticking happily in his hands. From then on, Otto was never late, and he never forgot his kind teacher."),
    ("MEDIUM", "High on a rocky mountain, a tiny seed landed in a crack between the stones. The wind was cold and the soil was thin. \"I'm too small to grow up here,\" the seed worried. But a gentle rain fell, and the warm sun peeked through the clouds. Bit by bit, the seed pushed out a thin green shoot. It was hard work. The wind pushed and the nights were chilly, but the little plant held on tightly to the mountain. Seasons passed. The shoot grew into a strong young tree with deep roots gripping the rock. Birds came to rest in its branches, and travelers stopped to sit in its shade. The tree looked out over the whole valley below. \"I did it,\" it whispered proudly. Even in the hardest place, a tiny seed had grown into something wonderful and strong."),
    ("MEDIUM", "A proud king wanted a grand painting of himself for the palace wall. He called for Rosa, a gentle painter known across the land. \"Make me look mighty and magnificent!\" the king demanded. Rosa studied the king carefully. Instead of only painting his golden crown, she painted the small, kind things she noticed: how he patted his dog, how he smiled at the palace children, how he helped an old servant carry water. When Rosa unveiled the painting, the king frowned at first. Then he looked closer and saw himself being kind and warm. Slowly, he began to smile. \"This is better than mighty,\" he said softly. \"This shows who I truly am.\" The king hung the painting proudly and, from that day on, tried to be even kinder. Rosa had shown him that true greatness comes from a good and gentle heart."),
    ("MEDIUM", "Mira loved building things from spare parts. One morning, she noticed the laundry basket was always full of lonely socks with no matches. Their poor cat, Biscuit, kept batting them under the couch. Mira decided to help. She spent all Saturday in the garage with bottle caps, wire, and an old fan. By dinner, she had built a small rolling robot with two soft claws. She called it the Sock Sorter. It rolled around the house, gathered every lost sock, and lined them up in neat pairs. Her family cheered and clapped. Even Biscuit purred and rubbed against it. From that day on, no sock was ever lonely again. Mira smiled and started planning her next helpful invention: maybe a machine to water the garden."),
    ("MEDIUM", "Ollie the owl was afraid of the dark. While other owls flew and hunted at night, Ollie hid in his hollow tree, shivering. His wise grandmother noticed and gently coaxed him outside. \"Look up,\" she whispered. Ollie peeked out and saw the moon shining like a silver coin. Soft fireflies blinked among the branches, and the stars sparkled overhead. \"The night is not empty,\" Grandmother said. \"It is full of quiet light.\" Ollie took a slow breath and spread his wings. He glided over the meadow, feeling the cool breeze. The dark was not scary after all; it was calm and beautiful. Now Ollie loves flying at night, hooting happily under the stars. He even helps younger owls feel brave, telling them, \"The dark is a friend.\""),
    ("HARD", "Milo the little dog loved to chase butterflies. One warm afternoon, he chased one so far that he did not know where he was. The streets looked strange, and none of the smells felt like home. Milo felt worried, but he did not give up.\n\nHe remembered that his home was near a bakery that smelled of fresh bread. So Milo lifted his nose and sniffed the air. He walked past a busy park, then past a small pond where ducks splashed. A kind girl saw his collar and gave him a bowl of water. Milo thanked her with a happy bark and kept going.\n\nAfter a while, he caught it: the warm, sweet smell of bread. His tail began to wag. He followed the smell down one street, then another, until he saw the blue door of his own house.\n\nHis family had been searching everywhere. When they saw Milo, they cheered and hugged him tight. His owner, a boy named Sam, gave him a treat and a soft pat.\n\n\"You found your way back,\" Sam said with a smile. That night, Milo slept happily by the warm fire, glad to be home again at last."),
    ("HARD", "Lena's little brother, Theo, was turning ten, but their family had very little money that year. Theo said he did not mind, yet Lena wanted to make the day special anyway.\n\nShe thought hard about what to do. She could not buy a big gift, but she could make one with her own hands. All week, Lena worked quietly in her room after school. She painted a poster of Theo's favorite superhero, saved her coins for balloons, and baked a lopsided but tasty chocolate cake.\n\nShe also had a plan. She asked Theo's friends to hide in the garden after dark. It was hard to keep the secret, because Theo kept asking questions. Lena just smiled and said nothing.\n\nOn the big day, Lena led Theo outside, telling him she needed help. Suddenly, the lights flicked on and everyone jumped out.\n\n\"Surprise!\" they shouted.\n\nTheo froze, then laughed so hard he almost cried. He hugged Lena tight. \"This is the best birthday ever,\" he said.\n\nThey ate cake, played games, and danced in the garden under the stars. Lena felt proud and happy. She learned that the best gifts do not cost much money at all."),
    ("HARD", "Priya had been waiting weeks for the school trip to the zoo. When the big day came, she grabbed her notebook and pencil, ready to draw every animal she saw.\n\nFirst, the class visited the tall giraffes, who nibbled leaves from high branches. Then they watched the monkeys swing and tumble, making everyone giggle. Priya sketched fast, trying to catch each pose.\n\nBut her favorite stop was the penguin pool. She stayed at the glass, watching the little birds waddle and dive. One small penguin swam right up to her and tilted its head, as if it were studying her too.\n\n\"I think it likes you,\" said the zookeeper with a smile. She explained that this penguin was the youngest of the group and very curious.\n\nPriya pressed her hand to the glass, and the penguin bobbed its head. It felt like they were sharing a quiet secret.\n\nWhen it was time to leave, Priya waved goodbye. She looked down at her notebook, now full of drawings.\n\nOn the bus home, she showed her friends every picture. But the penguin sketch was her favorite. \"One day,\" she said, \"I want to learn all about animals.\" And she truly meant it."),
    ("HARD", "When Jonah woke up, the whole world outside his window was white. Snow had fallen all night, covering the yard, the fence, and even the mailbox in a soft blanket.\n\nHe rushed downstairs and pulled on his boots, coat, and mittens. His older sister, Amara, came too. The snow crunched under their feet as they stepped outside.\n\n\"Let's build something,\" Jonah said.\n\nThey rolled three big snowballs and stacked them tall. Amara found two sticks for arms, and Jonah added stones for the eyes and a carrot for the nose. Their snowman looked cheerful and round.\n\nNext, they had a friendly snowball toss, laughing as the soft snow burst against their coats. Their cheeks turned pink from the cold, but they did not want to stop.\n\nSoon, the neighbor kids came out too, and everyone joined in. They made snow angels, flapping their arms and legs in the fresh powder.\n\nWhen their fingers grew cold, they hurried inside. Their mother had warm cocoa waiting, with tiny marshmallows floating on top.\n\nJonah and Amara sat by the window, sipping their drinks and watching more snow drift down. \"This was the best morning,\" Jonah said. Amara nodded, smiling. It truly was."),
    ("HARD", "Sofia noticed the new boy sitting alone at lunch every day. His name was Daniel, and he had just moved from another city. He always looked down at his tray, saying nothing.\n\nSofia felt a little shy, but she remembered how lonely she had felt on her own first day. So she took a deep breath and walked over.\n\n\"Can I sit here?\" she asked.\n\nDaniel looked up, surprised, then nodded. At first, neither of them knew what to say. Then Sofia spotted the comic book poking out of his bag.\n\n\"You like those too?\" she asked. \"That one is my favorite!\"\n\nDaniel's face lit up. Suddenly, the words came pouring out. They talked about heroes, funny characters, and which stories were the best. The lunch bell rang far too soon.\n\nThe next day, Daniel waved Sofia over to sit with him. Soon they were eating together every day, sharing snacks and drawing their own comics.\n\nWeeks later, Daniel told her, \"Thank you for talking to me. I was so nervous here.\"\n\nSofia smiled. \"Everyone needs a friend,\" she said.\n\nFrom then on, whenever a new student arrived, Sofia and Daniel were the first to say hello."),
    ("HARD", "Grandpa gave Nadia a tiny silver seed in a small cloth bag. \"This is a special seed,\" he said with a wink. \"Plant it, care for it, and see what happens.\"\n\nNadia was not sure she believed him, but she planted the seed in a pot on her windowsill. Every morning, she gave it water and turned it toward the sun. Every night, she whispered a kind wish to it before bed.\n\nDays passed, and nothing happened. Nadia felt like giving up, but she kept watering it anyway. Then, one morning, she saw a tiny green sprout poking through the soil.\n\nShe cheered so loudly that her whole family came running. The sprout grew fast after that. In a week it reached her knee. In a month it stood taller than she was, with wide green leaves.\n\nThen it bloomed. The flower was unlike any she had seen, with petals that shimmered like gold in the light.\n\n\"How did it grow so beautifully?\" Nadia asked Grandpa.\n\nHe smiled. \"The magic was never in the seed,\" he said. \"It was in your patience and care.\"\n\nNadia looked at the flower and understood. She had grown a little too."),
    ("HARD", "Kofi loved the beach more than anywhere in the world. On a bright summer day, his family packed towels, snacks, and a bright red bucket for the long drive to the sea.\n\nWhen they arrived, Kofi kicked off his sandals and ran to the water. The waves were cool and tickled his toes. He laughed as they rushed in and out.\n\nHis older cousin, Ama, challenged him to build the biggest sandcastle on the beach. They worked together for hours, digging, patting, and shaping. They added towers, a moat, and even a bridge made of shells.\n\nWhile they built, Kofi found a tiny crab scuttling near the water. He watched it dig into the wet sand and disappear. \"Look how fast it is!\" he said.\n\nLater, they floated on their backs and watched the seagulls glide across the sky. The sun warmed their faces.\n\nAs the day ended, the family gathered to watch the sunset paint the sky pink and orange. Kofi looked back at their footprints in the sand, already washing away with the waves.\n\n\"Best day ever,\" he whispered.\n\nOn the drive home, sandy and tired, Kofi fell asleep with a smile, dreaming of the sea."),
    ("HARD", "In a cozy hole beneath an old barn lived a small mouse named Pip. Pip was the tiniest of all his brothers and sisters, and they often teased him for being afraid of everything.\n\nOne evening, the mouse family ran out of food. The only place to find more was across the wide barn floor, where the farmer's cat liked to nap. Everyone was too scared to go.\n\nPip's tummy rumbled, and he thought of his little sisters going hungry. He took a deep breath. \"I will go,\" he said.\n\nHis heart pounded as he crept along the wall, quiet as a shadow. He froze when the cat stirred, then tiptoed on when it settled back to sleep.\n\nAt last, he reached a basket of grain. He filled his tiny cheeks and stuffed a few seeds into a leaf pouch. Then, slow and careful, he made his way back home.\n\nWhen he returned, his family cheered. \"You are the bravest mouse of all!\" they said.\n\nPip smiled shyly. He learned that being brave did not mean feeling no fear. It meant doing the right thing, even when your knees were shaking. And from that night on, no one teased little Pip again."),
    ("HARD", "Pancake was a small brown puppy with floppy ears and busy paws. His new friend, Leo, wanted to teach him to sit. Every morning, Leo held a treat above Pancake's nose and said, \"Sit!\" But Pancake only barked, spun in circles, and chased his own tail. Day after day, nothing worked. Leo began to feel frustrated, but he did not give up. He asked his aunt, who trained dogs, for advice. \"Be patient and calm,\" she said. \"Reward even the smallest try.\" So the next day, Leo spoke softly. When Pancake's back legs bent just a little, Leo cheered and gave him the treat right away. Pancake's tail wagged wildly. He liked that! The puppy tried again, bending a bit more. Leo cheered again. By the end of the week, Pancake finally lowered his bottom all the way to the floor and sat perfectly still. Leo was so happy he could have jumped to the moon. He hugged Pancake and gave him three treats. From then on, whenever Leo said \"Sit,\" Pancake sat proudly, waiting for his reward. Leo learned that patience and kindness taught more than shouting ever could, and Pancake learned that sitting brought treats."),
    ("HARD", "Every summer, Aisha visited her grandma who lived in a small house near the sea. This year, Grandma had a surprise. \"Today,\" she said, \"I will teach you my secret soup.\" Aisha grinned and tied on an apron. They walked to the garden and picked ripe tomatoes, fresh basil, and a handful of green beans. Grandma showed Aisha how to chop the vegetables safely and stir the pot slowly. \"The secret,\" Grandma whispered, \"is to add love and a pinch of patience.\" The kitchen filled with a warm, delicious smell. While the soup cooked, they sat on the porch and Grandma told stories about when she was a girl. Aisha listened closely, laughing at the funny parts. When the soup was ready, they poured it into two big bowls. Aisha took a careful sip. It was the best soup she had ever tasted. \"Now this recipe is yours too,\" Grandma said, squeezing her hand. Aisha promised to make it for her own family one day and to pass the secret along. On the train home, Aisha wrote the recipe in a little notebook so she would never forget. She knew the real secret was the time they spent together."),
    ("HARD", "Finn was a young orange fish who lived at the edge of the coral reef. He had always been told to stay close to home, but he was curious about the colorful world beyond the rocks. One bright morning, Finn swam a little farther than usual. He saw purple coral shaped like flowers, tall green plants swaying in the current, and a shy crab hiding under a shell. It was more beautiful than he had ever imagined. But soon Finn realized he had swum too far and did not know the way back. He felt worried. Just then, a wise old sea turtle glided by. \"Are you lost, little one?\" she asked kindly. Finn nodded. The turtle smiled and said, \"Follow the sunlight toward the shallow water, and you will find your reef.\" Finn thanked her and swam upward toward the glowing light. Bit by bit, he recognized the familiar coral and the rocks near his home. His family was so happy to see him. Finn told them about the crab and the flowers and the kind turtle. From then on, he explored a little more each day, but always remembered the turtle's lesson: to find your way, look for the light."),
    ("HARD", "Rosa loved looking at the moon through her bedroom window. She dreamed of visiting it one day. In her dream that night, a shiny silver rocket landed in her backyard, and a friendly robot invited her aboard. Rosa buckled her seatbelt as the rocket rumbled and lifted off. Up, up it went, past the clouds, past the twinkling stars. Through the window, Rosa watched the Earth shrink into a small blue marble. Soon they landed softly on the moon. Rosa stepped out in her puffy spacesuit and bounced high with every step, because the moon has less gravity. She left footprints in the gray dust and waved at the Earth far away. The robot showed her deep craters and shiny rocks that sparkled like glass. Rosa collected one small stone to remember her trip. \"It is quiet and peaceful up here,\" she said, gazing at the endless sky. But soon it was time to return home. The rocket carried her safely back, and she landed gently in her yard. Rosa woke up in her cozy bed, sunlight streaming in. On her pillow sat a tiny gray stone that sparkled. She smiled, wondering if her adventure had been real after all."),
    ("HARD", "The school was raising money for a new library, so the students planned a bake sale. Jordan wanted to help, but he had never baked anything before. His friend Nina offered to teach him how to make cookies. On Friday evening, they measured flour, cracked eggs, and mixed in chocolate chips. The kitchen got a little messy, and Jordan even spilled sugar on the floor, but they laughed and cleaned it up. When the cookies came out of the oven, they smelled warm and wonderful. The next morning, they set up a table with plates of cookies, muffins, and lemonade. At first, only a few people stopped by. Jordan felt disappointed. Then Nina made a bright, colorful sign that said, \"Cookies for a Cause!\" Soon a crowd gathered, and the treats sold quickly. Parents, teachers, and students all wanted a taste. By noon, everything was sold out. They counted the money and were amazed at how much they had raised. Their teacher announced that the whole school had earned enough for many new books. Jordan felt proud that his cookies had helped. He learned that baking was fun, and that working together for a good cause was even sweeter than the treats."),
    ("HARD", "On a warm summer night, a tiny firefly named Glow felt sad. All the other fireflies had bright, dazzling lights, but Glow's light was small and faint. He hid in the tall grass, sure that no one would notice him. Nearby, a group of children were camping in the woods. A little girl had wandered a bit too far from the tents and could not find her way back in the dark. She was frightened. Glow saw her tears and wanted to help, even though his light was small. He fluttered close and let his little light shine. It was not very bright, but in the deep darkness, even a small light was easy to see. The girl followed Glow's tiny glow, step by step, back toward the warm campfire. When she reached the tents, she smiled and whispered, \"Thank you, little light.\" Glow felt his heart swell with joy. The other fireflies had seen everything and gathered around him. \"Your light is small,\" they said, \"but it did something big tonight.\" Glow finally understood that the size of his light did not matter. What mattered was how he used it. From that night on, Glow shone proudly, no matter how small."),
    ("HARD", "In a golden autumn field stood a scarecrow named Pip. His job was to keep the crows away from the corn, and he did it well. But standing alone all day made Pip feel lonely. He watched the leaves turn red and orange and wished he had a friend. One chilly morning, a small crow landed on his shoulder. Pip expected the crow to fly off in fear, but it did not. \"You look lonely,\" the crow said. \"May I sit with you?\" Pip was surprised and happy. \"But aren't you afraid of me?\" he asked. The crow laughed. \"You have never once tried to hurt me. Why would I be afraid?\" So the crow stayed, and soon other birds came too. They perched on Pip's arms and told him about the faraway places they had seen. Pip realized the birds only nibbled a little corn, leaving plenty for the farmer. When the farmer came to check his field, he saw the happy scarecrow surrounded by birds and smiled. \"You keep the field lively,\" he said, patting Pip's straw hat. That autumn, Pip was never lonely again. He learned that being kind, even to those you are supposed to chase away, can bring the best friendships."),
    ("HARD", "Wren was a young bird who had just left her family's cozy home. Now it was time to build a nest of her own. But Wren had never done it before, and she was not sure where to start. She gathered a few twigs and tried to stack them on a branch, but they kept tumbling to the ground. Wren felt discouraged. An older sparrow flying by stopped to watch. \"Building takes practice,\" the sparrow said kindly. \"Weave the twigs together, and add soft grass and feathers to hold them.\" Wren thanked her and tried again. This time she wove the twigs carefully, tucking them under and over one another. She flew back and forth, collecting soft moss and fluffy feathers. It took all day, and her wings grew tired, but she did not stop. As the sun began to set, Wren finally finished. Her nest was round and snug, sitting safely in the fork of a strong branch. She hopped inside and found it warm and comfortable. Wren was so proud of what she had made all by herself. The next spring, she filled her nest with tiny eggs. She had learned that hard work and a little help can build something wonderful."),
    ("HARD", "Mila and her little brother Sam entered the summer sandcastle contest at the beach. All around them, other kids built tall towers and wide walls. Mila wanted to win, so she worked fast and did not let Sam help. Soon her castle grew high, but the top part cracked and slid down. She frowned at the broken sand. Sam sat beside her and started patting little shells into the sides of the wet wall. Then he dug a small moat and filled it with seawater using his bucket. Mila watched him and smiled. Together, they rebuilt the castle, slower this time. She shaped the towers while Sam added shells, a bridge, and a tiny flag made from a leaf. When the judge walked by, she stopped and clapped. Their castle was not the tallest, but it was the most joyful one on the whole beach. The judge gave them a blue ribbon for teamwork. Mila hugged her brother. She had learned that building something together was more fun than building it alone. As the sun set, the two of them sat by their castle, proud and happy, letting the warm waves tickle their toes before the tide slowly came in."),
    ("HARD", "Penny wanted a new bike, so she decided to open a lemonade stand on her street. She squeezed fresh lemons, added sugar and cold water, and made a big sign. On the first morning, only two people stopped by, and Penny felt discouraged. She almost gave up. Then she noticed that the day was very hot and people looked tired as they walked past. She had an idea. Penny moved her stand closer to the park, where families rested in the shade. She added slices of orange for a fun twist and offered a free cup to anyone who was thirsty and had no money. Soon, word spread. Children, parents, and even the mail carrier came to buy her sweet, cool lemonade. A kind neighbor told her friends, and the line grew longer. By the end of the week, Penny had earned enough for her bike, plus a little extra. Instead of keeping it all, she gave the extra coins to a boy who wanted lemonade but had spent his last dollar. Penny rode home on her shiny new bike, feeling proud. She had learned that a little kindness could make a small stand into something wonderful."),
    ("HARD", "At the fair, Theo held a bright red balloon on a long string. He loved how it bounced above his head in the breeze. But when he reached down to tie his shoe, the string slipped from his fingers. The balloon floated up, up, and away into the blue sky. Theo watched it drift over the treetops and felt a lump in his throat. A little girl nearby began to cry too, for she had wanted a balloon of her own. Theo did not chase after his balloon, because he knew it was gone. Instead, he had an idea. He walked to the balloon seller and used his last coins to buy one green balloon. Then he knelt down and handed it to the crying girl. Her face lit up with a huge smile. Just then, a gust of wind pushed Theo's red balloon back down, and it landed gently in a nearby bush. A helpful clown pulled it free and returned it to him. Now Theo had his balloon again, and the girl had hers. The two children walked side by side through the fair, their balloons dancing happily together in the warm afternoon sun."),
    ("HARD", "Toby the turtle loved to watch the animals race across the meadow every spring. He always wanted to join, but he was slow, and the rabbits and deer laughed at the idea. This year, Toby decided to enter anyway. On race day, the animals lined up at the start. When the whistle blew, everyone dashed ahead, leaving Toby far behind. He did not mind. He walked steadily, step by step, enjoying the flowers and the warm sun. Ahead of him, the fast rabbit grew tired and stopped to nap under a tree. The deer got distracted by a stream and wandered off to drink. One by one, the quick animals lost their way or ran out of energy. Toby kept going, never stopping, never quitting. The other racers had forgotten that finishing mattered more than speed. Slowly, Toby reached the top of the hill and saw the finish line. He crossed it just as the rabbit woke up and gasped. The whole meadow cheered for the little turtle who never gave up. Toby did not win because he was fast. He won because he was steady and patient. From then on, no one ever laughed at slow Toby again."),
    ("HARD", "In a narrow shop full of ticking clocks lived a kind old clockmaker named Mr. Alden. He had spent his whole life fixing broken clocks and watches for the people of his town. He never charged much, and he always had a warm smile for every customer. One rainy evening, a poor young boy came into the shop holding a small, broken pocket watch. It had belonged to his grandfather, and it was the only thing he had left of him. The boy had no money to pay, and he looked down at his shoes, ashamed. Mr. Alden gently took the watch and studied it under his lamp. \"This is a fine old watch,\" he said kindly. He worked late into the night, cleaning each tiny gear and spring with great care. By morning, the watch ticked once more, keeping perfect time. When the boy returned, Mr. Alden placed the watch in his hands and refused to take any payment. \"Some things,\" he said, \"are worth more than money.\" The boy's eyes filled with happy tears. Years later, that boy grew up to become a clockmaker too, always remembering the kind old man who had once helped him for free."),
    ("HARD", "Greta lived with her father in a tall lighthouse by the sea. Her father was the keeper, and every night he lit the great lamp to guide the ships safely home. One evening, a powerful storm rolled in. The wind howled and the waves crashed against the rocks. Just as the storm grew fiercest, Greta's father slipped on the wet stairs and hurt his ankle. He could not climb up to light the lamp. \"The ships need the light,\" he said, worried. \"Without it, they could lose their way.\" Greta was scared, but she knew she had to help. She grabbed the box of matches and began the long climb up the winding steps of the lighthouse. The wind shook the walls, but she kept going. At the top, her hands trembled as she struck a match and lit the great lamp. Its bright beam cut through the darkness and swept across the stormy sea. Far out on the water, the sailors saw the light and steered their ship safely toward the harbor. By morning, the storm had passed. The grateful sailors came to thank the brave young girl who had lit the way. Greta hugged her father, proud that she had helped bring everyone home safely."),
    ("HARD", "Nutkin the squirrel loved to play. All autumn long, while the other squirrels gathered acorns and nuts, Nutkin chased butterflies and napped in the warm sun. \"Winter is far away,\" he told his friends. \"There is plenty of time to gather food later.\" But his wise friend Hazel shook her head. \"Winter comes faster than you think,\" she warned. Nutkin did not listen. He kept playing while the days grew shorter and the leaves turned gold and fell. One cold morning, Nutkin woke to find frost on the ground. Winter had arrived at last, and his little store was almost empty. He searched everywhere, but the nuts were buried under snow. Nutkin felt worried and cold. Just then, Hazel found him shivering by a bare tree. She had gathered more than enough food, and she kindly shared her acorns and seeds with him. Nutkin was very grateful. Together, they waited out the long winter, warm and safe in Hazel's cozy nest. When spring finally came, Nutkin made a promise. That autumn, he worked hard alongside his friends, gathering nuts every single day. He had learned that a little effort early on could keep him safe when the hard times came, and he never forgot Hazel's kindness."),
    ("HARD", "Mira loved to build things. Her room was full of gears, tape, and old bottle caps. One rainy afternoon, she decided to build a machine that could water the garden while she was at school.\n\nAt first, nothing worked. The tubes leaked, and the little motor buzzed but never spun. Mira felt like giving up. She sat down and stared at her cardboard notebook, full of crossed-out ideas.\n\nThen she noticed something. The rain outside was rolling down the window and dripping into a flower pot. Water could move on its own if she just tilted the tubes! Mira grinned and rebuilt her machine, letting the water slide gently downhill.\n\nThe next morning, she flipped the switch. Slowly, steadily, water trickled through the tubes and sprinkled every plant in the garden. The tomatoes got a drink. The roses got a drink. Even the tiny herbs got a drink.\n\nMira's family clapped when they saw it. Her little brother called her \"the garden genius.\" Mira laughed and wrote a new note in her book: \"Sometimes the best idea is already in front of you.\"\n\nFrom that day on, she kept inventing, one small, clever idea at a time."),
    ("HARD", "Ollie was a young owl who was afraid of the dark. This was a problem, because owls are supposed to love the night. While other owls glided happily under the moon, Ollie hid in his tree, shivering at every shadow.\n\nOne evening, his older sister asked him why he was so scared. \"I can't see what's out there,\" Ollie whispered. \"The dark feels so big and empty.\"\n\nHis sister smiled kindly. \"Come with me,\" she said. \"Let me show you what the dark is really made of.\"\n\nTogether they flew out into the night. His sister pointed at the twinkling stars, the glowing moon, and the soft blue light on the sleeping fields. She showed him fireflies blinking like tiny lanterns and a silver river shining below.\n\nOllie realized the dark was not empty at all. It was full of quiet, gentle beauty that only came out at night.\n\nSlowly, his fear melted away. He spread his wings and soared higher, feeling the cool air and watching the stars.\n\n\"The night is our friend,\" his sister said.\n\nOllie nodded happily. From then on, he loved flying under the stars, and he was never afraid of the dark again."),
    ("HARD", "Cassie was a small green caterpillar who lived on a leafy branch. Every day she munched leaves and watched the butterflies drift by like floating flowers. \"I wish I could fly like that,\" she sighed.\n\nHer friend, an old ladybug, chuckled. \"Be patient, Cassie. Big changes take time.\"\n\nCassie kept eating and growing. One morning, she felt strange and sleepy. Something inside told her it was time. Slowly, she spun a small, snug case around herself called a chrysalis. Then everything went quiet and still.\n\nInside, Cassie waited. She could not see the sun or her friends. She wondered if anything was happening at all. But deep inside the chrysalis, her body was changing in ways she could not imagine.\n\nDays passed. Then, one sunny morning, the case cracked open. Cassie pushed her way out and unfolded a pair of bright, beautiful wings. She had become a butterfly!\n\nAt first her wings were soft and crumpled. She waited for them to dry in the warm sun. Then, gently, she flapped them and lifted into the air.\n\nCassie soared over the branch where she once crawled. \"The old ladybug was right,\" she thought happily. \"The best changes are worth the wait.\""),
    ("HARD", "Bruno the bear had found the best blackberry bush in the whole forest. The berries were fat, sweet, and shiny. Bruno wanted every single one for himself.\n\nWhen a rabbit hopped by and asked for a few berries, Bruno grumbled, \"No, these are mine.\" When a squirrel asked, Bruno turned away. Soon the other animals stopped visiting him, and Bruno ate alone.\n\nBut there were far too many berries for one bear. They began to spoil, dropping to the ground and rotting. Bruno felt his belly ache from eating too many, and he felt something else too. He felt lonely.\n\nOne evening, he saw the rabbit and squirrel laughing together, sharing a small pile of acorns. They looked so happy. Bruno realized that having everything was not the same as being happy.\n\nThe next morning, Bruno gathered a big basket of berries and carried it to his neighbors. \"I'm sorry,\" he said softly. \"Would you like to share these with me?\"\n\nThe animals cheered. They sat together, eating berries and telling stories until the sun went down.\n\nBruno smiled. The berries tasted sweeter than ever. He learned that sharing did not make him have less. It made him have friends."),
    ("HARD", "Finn was known throughout the meadow as the cleverest fox around. But Finn was also kind, and that made him special.\n\nOne autumn day, a heavy storm knocked branches across the only path to the river. The smaller animals could not get past to drink, and they were growing thirsty and worried.\n\nThe animals came to Finn. \"You are so clever,\" said a mouse. \"Can you help us?\"\n\nFinn studied the pile of branches. Pushing them was too hard, and climbing over was too dangerous for the little ones. He thought carefully, tapping his paw.\n\nThen he had an idea. \"We don't need to move the branches,\" he said. \"We need to use them.\"\n\nFinn showed the animals how to arrange the fallen branches into a smooth little bridge that led right over the muddy part to the water's edge. Working together, they laid each branch in place.\n\nSoon a neat path stretched all the way to the river. The animals crossed easily and drank their fill.\n\n\"Thank you, Finn!\" they cheered.\n\nFinn smiled. \"Being clever is good,\" he said. \"But being clever and helpful is even better.\"\n\nFrom then on, the animals knew Finn was not just the smartest fox, but the kindest too."),
    ("HARD", "In a sunny little town, there was a small robot named Pip. Pip had one important job. Every morning, he rolled through the park and tidied up.\n\nPip picked up dropped wrappers, straightened fallen benches, and gathered scattered leaves. He worked cheerfully, beeping a happy tune as he went. The park always looked bright and clean, and the townspeople loved it.\n\nBut one morning, Pip found the park in a terrible mess. A windy night had blown papers everywhere and knocked over the trash bins. There was so much to clean that Pip did not know where to start. His little lights blinked sadly.\n\nJust then, a group of children arrived to play. They saw Pip looking overwhelmed. \"Let's help!\" one child shouted.\n\nThe children grabbed bags and began picking up trash beside Pip. Together, they worked quickly, laughing and racing to see who could gather the most. Pip beeped with joy.\n\nIn no time, the park was spotless again. The children high-fived Pip's metal hand.\n\n\"Thank you,\" Pip beeped warmly. \"I could not have done it alone.\"\n\nFrom then on, the children helped Pip every weekend. The park stayed cleaner than ever, and Pip had made some wonderful new friends."),
    ("HARD", "Dev loved solving mysteries. He carried a small notebook everywhere and called himself the neighborhood detective.\n\nOne afternoon, his friend Aria ran up, upset. \"My swimming medal is gone!\" she cried. \"I left it on the porch table, and now it's missing.\"\n\nDev flipped open his notebook. \"Don't worry,\" he said. \"Let's find the clues.\"\n\nFirst, he looked at the table. He noticed tiny muddy paw prints leading across the porch and down the steps. \"An animal was here,\" Dev said thoughtfully.\n\nHe followed the little prints across the grass. They led toward the big oak tree at the edge of the yard. Dev looked up and spotted a squirrel's nest tucked in the branches.\n\nSomething shiny glinted inside it. Dev smiled. \"The squirrel took the medal because it was shiny!\"\n\nCarefully, Aria's dad brought a ladder and reached up. Sure enough, the medal was tucked among the leaves. The squirrel chattered and scampered off to a higher branch.\n\nAria hugged her medal. \"Dev, you did it! How did you know?\"\n\nDev grinned and closed his notebook. \"A good detective just follows the clues.\"\n\nThey both laughed, watching the squirrel peek down at them from the tree. Mystery solved."),
    ("HARD", "In a green meadow, four animal friends decided to start a band. Toby the frog played a hollow log like a drum. Lily the cricket chirped a lovely tune. Max the bird whistled bright notes, and Bella the mouse shook a seed pod like a rattle.\n\nThere was just one problem. When they all played together, it sounded terrible. Toby drummed too fast, Lily chirped too slow, and Max whistled whenever he liked. The noise scared the butterflies away.\n\nThe friends felt frustrated. \"Maybe we're just not good musicians,\" sighed Bella.\n\nBut Max had an idea. \"What if we listen to each other instead of playing over each other?\"\n\nSo they tried again. This time, Toby started with a slow, steady beat. Bella matched him with her rattle. Then Lily added her chirp, and finally Max whistled softly on top.\n\nThis time, the sounds blended into a beautiful melody. The music floated across the meadow, gentle and sweet. The butterflies came back and danced in the air. Even a wise old turtle nodded along.\n\nThe four friends beamed at each other. They had learned that making music together meant listening as much as playing.\n\nFrom that day on, the Meadow Melody Band played every evening, filling the meadow with joyful song."),
    ("HARD", "High in the snowy mountains, where the air was cold and the peaks touched the clouds, lived a young snow leopard named Nima. Her thick gray fur was covered in dark spots, perfect for hiding among the rocks and snow.\n\nNima was learning to explore the mountains on her own. One frosty morning, she wandered farther than ever before, climbing over icy ledges and leaping across snowy gaps.\n\nBut soon, thick clouds rolled in, and snow began to fall. Nima could not see the path home. She felt a little worried, sitting alone on a cold ledge as the wind whistled around her.\n\nThen Nima remembered what her mother had taught her. \"When you are lost, stay calm and use your senses.\" Nima closed her eyes and sniffed the air. She caught the faint, familiar smell of her family's den.\n\nSlowly and carefully, she followed the scent, padding softly through the snow. Step by step, the smell grew stronger. At last, she spotted the rocky cave where her mother waited.\n\nNima bounded inside, safe and warm. Her mother nuzzled her gently.\n\n\"You found your way,\" her mother purred proudly.\n\nNima felt brave and happy. She had faced the great mountains and found her way home."),
    ("HARD", "On Sunny Meadow Farm, the animals decided to hold a talent show. Everyone was excited to share what they could do.\n\nHen showed off her fancy egg-balancing trick. Horse galloped in graceful circles. Pig rolled in the mud and made silly shapes. The barnyard cheered for each act.\n\nBut little Duck sat quietly in the corner. \"I don't have a talent,\" she said sadly. \"I can't balance eggs or gallop or make mud shapes. I just waddle and quack.\"\n\nThe other animals tried to cheer her up, but Duck felt too shy to perform.\n\nWhen it was Duck's turn, she almost hid. Then a gentle breeze carried the sound of the farm pond, and Duck had an idea. She waddled to the center and began to quack a tune, a soft, cheerful song that bounced across the barnyard.\n\nThe animals grew quiet, then began to sway. Horse hummed along. Hen clucked to the beat. Soon the whole barnyard was singing together, following Duck's happy melody.\n\nWhen the song ended, everyone cheered louder than ever.\n\n\"Duck, your song brought us all together!\" said Pig. \"That's the best talent of all.\"\n\nDuck beamed. She realized that her simple quack was special after all, and she was never shy again."),
]


def _resolve_ailment_type_id(db) -> int:
    """Neutral 'Reading' ailment_type (created once) — same bucket Read It Loud uses.
    Story Teller isn't a disfluency sub-type either. Set AILMENT_TYPE_ID to override.
    """
    override = os.environ.get("AILMENT_TYPE_ID")
    if override:
        return int(override)
    row = db.execute(text("SELECT id FROM ailment_type WHERE name = 'Reading' LIMIT 1")).first()
    if row:
        return int(row[0])
    parent = db.execute(text("SELECT ailment_id FROM ailment_type ORDER BY id LIMIT 1")).first()
    if not parent:
        raise SystemExit("No ailment_type found. Create the Stutter ailment first, or set AILMENT_TYPE_ID.")
    db.execute(
        text(
            "INSERT INTO ailment_type (guid, name, ailment_id, created_at, last_modified_at) "
            "VALUES (gen_random_uuid(), 'Reading', :aid, now(), now())"
        ).bindparams(aid=int(parent[0]))
    )
    db.commit()
    row = db.execute(text("SELECT id FROM ailment_type WHERE name = 'Reading' ORDER BY id DESC LIMIT 1")).first()
    print(f"created ailment_type 'Reading' (id={row[0]}) under ailment_id={parent[0]}")
    return int(row[0])


def main() -> None:
    db = SessionLocal()
    try:
        ailment_type_id = _resolve_ailment_type_id(db)
        created = skipped = 0
        for difficulty, story in STORIES:
            exists = db.scalar(
                select(DisfluencyPhrase).where(
                    DisfluencyPhrase.exercise_type == "STORY_TELLER",
                    DisfluencyPhrase.sentence == story,
                )
            )
            if exists is not None:
                skipped += 1
                continue
            db.add(
                DisfluencyPhrase(
                    sentence=story,
                    ailment_type_id=ailment_type_id,
                    target_phoneme=None,
                    difficulty=Difficulty(difficulty),
                    exercise_type="STORY_TELLER",
                )
            )
            created += 1
        db.commit()
        print(
            f"Story Teller seeded: {created} created, {skipped} skipped "
            f"(ailment_type_id={ailment_type_id}, total defined={len(STORIES)})"
        )
    finally:
        db.close()


if __name__ == "__main__":
    main()
