from uuid import UUID

from sqlalchemy import ForeignKey, Integer, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import AbstractEntity


class ConversationHistory(AbstractEntity):
    """One row per turn in a child-AI conversation session.

    Turns belonging to the same session share the same session_id UUID.
    The session_id is generated by the backend when the first turn is created
    and returned to the client; subsequent turns pass it back.
    """

    __tablename__ = "conversation_history"

    user_id: Mapped[int] = mapped_column(
        ForeignKey("user.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Groups all turns of one conversation. Not a FK — just a shared UUID.
    session_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        nullable=False,
        index=True,
    )

    turn_number: Mapped[int] = mapped_column(Integer, nullable=False)

    # Child's speech — transcript stored for Claude conversation history.
    child_transcript: Mapped[str | None] = mapped_column(Text, nullable=True)
    child_audio_url: Mapped[str | None] = mapped_column(Text, nullable=True)

    # AI's response. (Only the text is stored — Ollie's audio is synthesised on
    # the fly and returned inline as base64, never persisted.)
    ai_text: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Raw disfluency events from the ML service, stored as JSON array.
    disfluency_events: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    user: Mapped["User"] = relationship()  # noqa: F821
